import type { NextPage } from 'next'
import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
// import { useRouter } from 'next/router'
import { useEffect } from 'react'
import Navbar from '../components/Navbar'
import { trpc } from '../utils/trpc'

const Home: NextPage = () => {
  // const router = useRouter()
  useSession({
    required: true,
    onUnauthenticated() {
      console.log('unauthenticated')
      // router.push('/')
    },
  })

  const userTopArtistsQuery = trpc.useQuery(
    ['spotify.getUserTopArtists', { timeRange: 'short_term', limit: 20 }],
    {
      keepPreviousData: true,
      refetchOnWindowFocus: false,
    }
  )

  useEffect(() => {
    console.log(userTopArtistsQuery.data)
  }, [userTopArtistsQuery])

  return (
    <>
      <Head>
        <title>Spotifaves</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <button onClick={() => signIn('spotify', { callbackUrl: '/' })}>LOG IN TO SPOTIFY</button>
        <button onClick={() => signOut()}>LOG OUT OF SPOTIFY</button>
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Create <span className="text-purple-300">T3</span> App
        </h1>
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500"></div>
      </main>
    </>
  )
}

export default Home
