import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { ReactNode } from 'react'
import SpotifyPlayer from 'react-spotify-web-playback'
import useVisibleOnScroll from '../hooks/useVisibleOnScroll'
import { useBoundStore } from '../store/index'
import CreatePlaylistFooter from './CreatePlaylistFooter'
import Navbar from './Navbar'

let accessToken: string | null = null

const Layout = ({ children }: { children: ReactNode }) => {
  const { data: session } = useSession()
  const uri = useBoundStore((state) => state.uri)
  const isPlaying = useBoundStore((state) => state.isPlaying)
  const { isVisibleOnScroll } = useVisibleOnScroll(300)
  const router = useRouter()

  if (session) {
    accessToken = session.accessToken as string
  }

  console.log(accessToken)

  console.log(uri)

  return (
    <>
      <Head>
        <title>Spotifaves</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {['/profile', '/artists', '/tracks', '/genres', '/recent'].includes(router.pathname) && (
        <Navbar />
      )}
      <main className="pt-8">
        <div className="container mx-auto max-w-7xl">{children}</div>
      </main>
      {['/artists', '/tracks', '/recent'].includes(router.pathname) && (
        <CreatePlaylistFooter
          isVisibleOnScroll={isVisibleOnScroll}
          title="Create Top Tracks playlist"
          description="This creates a playlist of your top 50 tracks."
        />
      )}
      {accessToken && (
        <div className="fixed bottom-0 left-0 right-0">
          <SpotifyPlayer
            autoPlay
            initialVolume={0.5}
            token={accessToken}
            play={isPlaying}
            uris={[uri && `spotify:track:${uri}`]}
            showSaveIcon
            styles={{
              bgColor: '#121212',
              color: '#fff',
              loaderColor: '#fff',
              sliderColor: '#1cb954',
              trackArtistColor: '#ccc',
              trackNameColor: '#fff',
            }}
          />
        </div>
      )}
    </>
  )
}

export default Layout
