import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import type { ReactNode } from 'react'
import SpotifyPlayer from 'react-spotify-web-playback'
import useVisibleOnScroll from '../hooks/useVisibleOnScroll'
import { useBoundStore } from '../store/index'
import CreatePlaylistFooter from './CreatePlaylistFooter'
import Navbar from './Navbar'

const Layout = ({ children }: { children: ReactNode }) => {
  const router = useRouter()
  const { data: session } = useSession()
  const uri = useBoundStore((state) => state.uri)
  const isPlaying = useBoundStore((state) => state.isPlaying)
  const setIsPlaying = useBoundStore((state) => state.setIsPlaying)
  const { isVisibleOnScroll } = useVisibleOnScroll(300)

  const accessToken = session?.accessToken ?? null

  return (
    <>
      <Head>
        <title>Spotifaves</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {['/profile', '/artists', '/tracks', '/genres', '/recent'].includes(router.pathname) && (
        <Navbar />
      )}
      <main className="pt-8">
        <div className="container mx-auto max-w-7xl">{children}</div>
      </main>
      <div className="fixed bottom-0 left-0 right-0">
        {['/artists', '/tracks', '/recent'].includes(router.pathname) && (
          <CreatePlaylistFooter isVisibleOnScroll={isVisibleOnScroll} />
        )}
        {accessToken && (
          <SpotifyPlayer
            autoPlay
            callback={(state) => !state.isPlaying && setIsPlaying(false)}
            initialVolume={0.5}
            token={accessToken}
            play={isPlaying}
            uris={uri ? [`spotify:track:${uri}`] : undefined}
            showSaveIcon
            styles={{
              bgColor: '#121212',
              color: '#fff',
              loaderColor: '#fff',
              sliderColor: '#1cb954',
              trackArtistColor: '#ccc',
              trackNameColor: '#fff',
            }}
          />
        )}
      </div>
    </>
  )
}

export default Layout
